export const SET_COMMON_LOADING = 'SET_COMMON_LOADING'
export const SET_COMMON_HEADER_MENU_OPEN = 'SET_COMMON_HEADER_MENU_OPEN'
//export const AUTH_SET_USER = 'AUTH_SET_USER'
//export const AUTH_UPDATE_USER_INFO = 'AUTH_UPDATE_USER_INFO'
//export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN'
//export const AUTH_UPDATE_STATE = 'AUTH_UPDATE_STATE'

