name: develop

on:
  push:
      branches:
        - develop
jobs:
  deploy:
    name: Upload to S3
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials from account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    #- name: Copy config file
    #  run: cp ./src/js/config/config.json.dev ./src/js/config/config.json

    - name: Download config file from S3
      env: 
        S3_CONFIG_BUCKET: ${{ secrets.S3_CONFIG_BUCKET_DEV }}
      run: |
        aws s3 cp s3://$S3_CONFIG_BUCKET/config.json ./src/client/js/config/ --quiet
        aws s3 cp s3://$S3_CONFIG_BUCKET/cognito-client-config.json ./src/client/js/config/ --quiet

    - name: Build by Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build

    - name: Copy Files to s3
      env: 
        S3_RESOURCE_BUCKET: ${{ secrets.S3_RESOURCE_BUCKET_DEV }}
      run: |
          aws s3 sync ./public s3://$S3_RESOURCE_BUCKET

    # Clear CloudFront Caches
    - name: Clear cache in CloudFront
      uses: chetan/invalidate-cloudfront-action@v1.2
      env:
        DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION_DEV }}
        PATHS: "/*"
        AWS_REGION: ap-northeast-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
